title: Lajbert
subtitle: Software engineer
description: >- # this means to ignore newlines until "baseurl:"
  My journey of 2D video game development.

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Blog
      url: /blog
    #- text: Gallery
      #url: /gallery
    #- text: Shop
      #url : /shop
    #- text: Contact
      #url : /contact


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.png
author: Lajbert
author_bio: "My name is Lajos, a software engineer who decided to chase his childhood dream of becoming a video game developer. I have a long road ahead of me until I can release my first game, but the path taking me there is already very rewarding. There are many great people around the internet who spends time, energy and even money to make great tutorials, shares their Github repos and distribute knowledge, and this blog is my attempt to pay my respect to them and follow their lead of giving back to the community.  
You’ll find tips, tricks, bits and pieces of what I learned while working on my project, which is also my learning path, so if you see something on my blog that is incorrect or can be done better, please leave a comment, so we all can learn something. Currently I’m working on a simple, generic 2D engine called Monolith engine, built on MonoGame framework, but many of my ideas are generic, and can easily be translated to your favorite language or game engine. Hopefully you’ll find something useful here. :)  
You can find the source code of the engine with same projects in my Github repo."
author_email: "lajbertgames@gmail.com"
author_location: Switzerland
author_website_url: "https://lajbert.github.io"
typewrite-text: A collection of tutorials and personal development experiences. Enjoy your stay!

# Experiences
author_work_experiences:
            - company_name: Google
              company_logo: google.png
              company_url: https://google.com
              designation: Software Engineer
              description: Worked on various Google Products
              visibility: true
            - company_name: Microsoft
              company_logo: microsoft.png
              company_url: https://microsoft.com
              designation: Azure Developer
              description: Worked on various Azure Cloud Products
              visibility: true

# Education
author_education_details:
              - college_logo: szte.jpg
                college_name: University of Szeged
                college_url: https://u-szeged.hu/
                college_degree: Computer Science BSc
                description: Bachelor of Computer Science
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: monogame.png
                project_title: [Arthive] Monolith Engine
                project_description: A free, open source, cross-platform 2D game engine based on MonoGame
                project_url: https://github.com/Lajbert/MonolithEngine
                visibility: true
              - project_thumbnail: hack4r.PNG
                project_title: Hack4r
                project_description: A Platform built for Hackers and Penetration Testers
                project_url: https://hack4r.com
                visibility: false

# social links
#twitter_username: johndoe
github_username:  Lajbert
#facebook_username: johndoe
#linkedin_username: johndoe
#behance_username: johndoe
#instagram_username: johndoe
#medium_username: johndoe
#telegram_username: johndoe
#dribbble_username: johndoe
#flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

#disqus_shortname: sujay-kundu
#hyvor_talk_website_id: 476

# wakatime username (coding activity)
#wakatime_username: Lajbert

# mailchimp embedded form url (newsletter):
#mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
# getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
formspree_email: lajbertgames@gmail.com

# releases - widget can be (sidebar, modal or embed)
# olvy_organization: devlopr
# olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: false
show_author_education_details: false
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
